#
#This is the list of all the VLANs that will be defined on Nexus, UCS and VMware
#
# Commenting out the following two variables will skip the iSCSI and/or FC configurations
configure_iscsi: "yes"
configure_fc: "yes"
configure_nfs: "yes"
#
# Uncomment and update the the following lines to setup NTP Server(s)
ntp_servers:
  - ip_address: "192.168.160.254"
#  - ip_address: "192.168.160.253"

# VLAN Names are adjustable and can be modified in here
#
native_vlan_name: 'Native-Vlan' # Native VLAN
oob_vlan_name: 'oob-mgmt' # Out of Band Mgmt VLAN
ib_vlan_name: 'ib-mgmt' # IN BAND Management VLAN
vm_vlan_name: 'vm-traffic' # VLAN to carry VM traffic on VDS
vmotion_vlan_name: 'vmotion' # vMotion VLAN
nfs_vlan_name: 'nfs-vlan' # NFS Traffic between ESXi and Storage
iscsiA_vlan_name: 'iscsi-a' # iSCSI-A VLAN (if needed)
iscsiB_vlan_name: 'iscsi-b' # iSCSI-B VLAN (if needed)
#
# lan_state should be set to 'present' to configure the objects
# In future, this parameter will be used for deleting the configuration
#
lan_state : 'present'
#
vlan_list:
  - name: "{{ native_vlan_name }}"
    id: '2'
    native: 'yes'
    state: "{{lan_state}}"
  - name: "{{ oob_vlan_name }}"
    id: '11'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ ib_vlan_name }}"
    id: '511'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vm_vlan_name }}"
    id: '611'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ vmotion_vlan_name }}"
    id: '3000'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ nfs_vlan_name }}"
    id: '3050'
    native: 'no'
    state: "{{lan_state}}"
    # ISCSI A and B VLANs should be deleted for Fiber-Channel-Only deployments
  - name: "{{ iscsiA_vlan_name }}"
    id: '3010'
    native: 'no'
    state: "{{lan_state}}"
  - name: "{{ iscsiB_vlan_name }}"
    id: '3020'
    native: 'no'
    state: "{{lan_state}}"
#
# VLANs definition below will be used to setup trunk ports on Nexus Switches
# all_vlans_list: for vpc_peer_link and UCS FI trunk ports
all_vlans_list: "11,511,611,3000,3010,3020,3050"
# storage_vlans_list: for vpc_peer_link and UCS FI trunk ports
storage_vlans_list: "511,3010,3020,3050"
# mgmt_vlans_list: for management switch trunk port
mgmt_vlans_list: "11,511"
#
native_vlan_id: "2"
#
vds_vlan_list:
  - name: "{{ vm_vlan_name }}"
    id: '611'
#
esxi_nfs_vlan: "3050"
#
esxi_vmotion_vlan: "3000"
#VSAN Parameters
#
vsan_list:
  - name: 'Fabric-A'
    vsan_id: '111'
    fcoe_vlan: '111'
    fabric: 'A'
  - name: 'Fabric-B'
    vsan_id: '112'
    fcoe_vlan: '112'
    fabric: 'B'
#
# Storage WWPNs (capture from storage system)
#
storage_node1_a: '20:01:00:A0:98:5B:4A:86'
storage_node2_a: '20:03:00:A0:98:5B:4A:86'
storage_node1_b: '20:02:00:A0:98:5B:4A:86'
storage_node2_b: '20:04:00:A0:98:5B:4A:86'
#
# UCS WWPNs (capture from the UCS Service Profiles)
#
ucs_host_01_a: '20:00:00:25:b5:bc:0a:00'
ucs_host_01_b: '20:00:00:25:b5:bc:0b:00'
#
#ucs_host_02_a: '20:00:00:25:b5:bc:0a:01'
#ucs_host_02_b: '20:00:00:25:b5:bc:0b:01'
#
# Storage iSCSI Target Interfaces
#
storage_node1_iSCSI_a: '192.168.10.251'
storage_node1_iSCSI_b: '192.168.20.251'
storage_node2_iSCSI_a: '192.168.10.252'
storage_node2_iSCSI_b: '192.168.20.252'
#
# VMware Configurations
#
esxi_username: root
esxi_password: "H1ghV0lt"
#
vcenter_dc: FlexPod-DC
vcenter_cluster: FlexPod-Management
#
vcenter_hostname: 10.50.160.100
vcenter_username: administrator@vsphere.local
vcenter_password: "H1ghV0lt!"
#
# DVS Parameters
#
dvs_name: "App_DVS"
dv_version: "6.6.0"
dv_uplink: "2"
dv_protocol: "lldp"
dv_operation: "both"
