---
# Global Variables for UCS Configurations
# These Variables are used across different roles in UCS configurations
# e.g. "organization" is used under san, lan, server and admin roles
# Adjust the variable values as per your requirements

#
#UCS Organization
organization: 'FlexPod'
# VMware High Traffic Adapter Policy
adapter_policy_name: 'VMware-HighTrf'
# IQN Pool Name
iqn_pool_name: 'IQN-Pool'
#
iscsi_a_pool_name: 'iSCSI-Pool-A'
iscsi_b_pool_name: 'iSCSI-Pool-B'
# iSCSI LAN Connectivity Policy Parameters
iscsi_lan_conn_policy: 'iSCSI-Boot'
iscsi_a_vnic_name: 'iSCSI-Boot-A'
iscsi_b_vnic_name: 'iSCSI-Boot-B'
#
# FC LAN Connectivity Policy Parameters
fc_lan_conn_policy: 'FCP-Boot'
# vHBA Names
vhba_a_name: 'vHBA-A'
vhba_b_name: 'vHBA-B'
# SAN Policy Paramters
san_policy_name: 'FC-Boot'
san_policy_vhba_a_name: 'Fabric-A'
san_policy_vhba_b_name: 'Fabric-B'
# Storage iSCSI Target
storage_iscsi_target: '<Storage System IQN>'
