################################################################################
#
# vCenter Setup Section
#
################################################################################
- hosts: localhost
#
  roles:
    - VMWAREvcenter

################################################################################
#
# Host Setup Section
#
################################################################################
- hosts: esxi_iscsi
  gather_facts: no
  serial: 1
  roles:
    - role: ESXIhosts
      when: configure_iscsi is defined
    - role: ESXIiscsi
      when: configure_iscsi is defined

- hosts: esxi_fc
  gather_facts: no
  serial: 1
  roles:
    - role: ESXIhosts
      when: configure_fc is defined

#- hosts: esxi_iscsi
#- hosts: esxi_fc
#  gather_facts: no
#  vars_files:
#    - "./vars/vsphere-main.yml"
#  roles:
#    - HostConfig
