---
# Playbook to setup UCS Server and SAN configurations
#
- hosts: ucs
  connection: local
  collections:
  - cisco.ucs
  gather_facts: no

  roles:
    #
    ### Create Configurations under SAN Tab in UCS
    #
    # IQN pools (when con)
    # WWNN pools
    # WWPN A and B Pools
    # VSAN A and VSAN B (if required)
    # vHBA Templates
    # enable VSAN trunking for uplink ports (if required)
    #- UCSsan
    #
    #
    ### Create Configurations under Server Tab in UCS
    #
    # UUID pools
    # Server Pool Configuration
    # Power Control Policy - No Power CAP
    # Modify default Maintenence policy - Add User Ack for reboot
    # VMware High Traffic Adapter Policy for VDS
    # Local Disk Policy - Ignore Local Disks
    # BIOS Policy
    # iSCSI Boot Policy (if required)
    # iSCSI Service Profile Template (if required)
    # FCP Boot Policy (if required)
    - UCSserver
