---
  # This task sets Ethnernet ports to L2 and enables interfaces
  - name: Enabling all ethernet and port-channel interfaces
    nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          mode: layer2
          enabled: yes
    with_list: "{{ all_interfaces + all_port_channels }}"

  # This task adds ports to the peer-link port-channels
  - name: Add Ports to peer-link Port-Channel
    nxos_lag_interfaces:
      config:
        - name: "{{ peerlink_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ vpc_interface_list }}"

  # This task adds ports to the management switch port-channels
  - name: Add Ports to management switch Port-Channel
    nxos_lag_interfaces:
      config:
        - name: "{{ mgmt_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ mgmt_interface_list  }}"

  # This task adds ports to the FI-A port-channels
  - name: Add Ports to FI-A Port-Channel
    nxos_lag_interfaces:
      config:
        - name: "{{ FI_A_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ FI_A_interface_list }}"

  # This task adds ports to the FI-B port-channels
  - name: Add Ports to FI-B Port-Channel
    nxos_lag_interfaces:
      config:
        - name: "{{ FI_B_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ FI_B_interface_list }}"

  # This task adds ports to the Storage-A port-channels
  - name: Add Ports to Storage-A Port-Channel
    nxos_lag_interfaces:
      config:
        - name: "{{ storage_A_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ storage_A_interface_list }}"

  # This task adds ports to the Storage-B port-channels
  - name: Add Ports to Storage-B Port-Channel
    nxos_lag_interfaces:
      config:
        - name: "{{ storage_B_PC[0].interface }}"
          members:
            - member: "{{ item.interface }}"
              mode: active
    with_list: "{{ storage_B_interface_list }}"

  # This task sets up speed, duplex and mtu settings for interfaces
  - name: Modify the mtu speed and duplex for ports
    nxos_interfaces:
      config:
        - name: "{{ item.interface }}"
          mtu: "9216"
          speed: "{{ item.speed }}"
          duplex: "{{ item.duplex }}"
    with_list: "{{ all_port_channels }}"
#
# Configure Trunk VLANs for Peer-Link and UCS FI Port-Channels
#
  - name: Enabling all vlans on peer-link and UCS FI Port-Channels
    nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ all_vlans_list }}"
    with_list: "{{ peerlink_PC + FI_A_PC + FI_B_PC }}"
#
# Configure VLANs for Peer-Link and UCS FI Port-Channels
#
  - name: Enabling management vlans on management Port-Channels
    nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ mgmt_vlans_list }}"
    with_list: "{{ mgmt_PC }}"
#
# Configure VLANs for Peer-Link and UCS FI Port-Channels
#
  - name: Enabling storage vlans on Storage Port-Channels
    nxos_l2_interfaces:
      config:
        - name: "{{ item.interface }}"
          trunk:
            native_vlan: "{{ native_vlan_id }}"
            allowed_vlans: "{{ storage_vlans_list }}"
    with_list: "{{ storage_A_PC + storage_B_PC }}"
