---
  - name: vCenter vDS Portgroup Creation
    vmware_dvs_portgroup:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      validate_certs: no
      switch_name: '{{ dvs_name }}'
      portgroup_name: '{{ item.portgroup_name }}'
      vlan_id: '{{ item.id }}'
      portgroup_type: earlyBinding
      num_ports: 120
      state: present
    with_list: "{{ vds_vlan_list }}"
