# Variables for ESXi Configuration
# Adjust the variable values as per your requirements
#
# Uplinks to be used by various Switch Configurations
#
mgmt_uplink1: vmnic0
mgmt_uplink2: vmnic1
#
dv_uplink1: "vmnic2"
dv_uplink2: "vmnic3"
#
vmotion_uplink1: vmnic4
vmotion_uplink2: vmnic5
#
#
vmotion_portgroup: "vMotion"
vmotion_vswitch: "vSwitch1"
vmotion_mask: 255.255.255.0
#
#mgmt_portgroup: "Management Network"
#mgmt_vlan: 511
#
default_portgroup: "VM Network"
#
nfs_portgroup: "VMKernel-Infra-NFS"
nfs_mask: 255.255.255.0
#
nfs_datastore_list:
  - mount: infra_swap
    server: 192.168.50.251
  - mount: infra_datastore_1
    server: 192.168.50.251
  - mount: infra_datastore_2
    server: 192.168.50.252
