---
  # Configure Service Profile Templates for iSCSI or FC
  # if configure_iscsi and/or configure_fc are set

  # iSCSI Service Profile Template
  #
  - name: Configure Service Profile Template for iSCSI
    ucs_service_profile_template:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "{{ iscsi_SPT_name }}"
      org_dn: "org-root/org-{{ organization }}"
      template_type: 'updating-template'
      uuid_pool: "{{ uuid_pool_name }}"
      lan_connectivity_policy: "{{ iscsi_lan_conn_policy }}"
      iqn_pool: "{{ iqn_pool_name }}"
      boot_policy: "{{ iscsi_boot_policy_name }}"
      maintenance_policy: 'default'
      power_control_policy: "{{ power_policy_name }}"
      local_disk_policy: "{{ local_disk_policy_name }}"
      server_pool: "{{ server_pool_name }}"
      bios_policy: "{{ bios_policy_name}}"
    when: configure_iscsi is defined
  #
  # FC Service Profile Template
  #
  - name: Configure Service Profile Template for FCP
    ucs_service_profile_template:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "{{ fc_SPT_name }}"
      org_dn: "org-root/org-{{ organization }}"
      template_type: 'updating-template'
      uuid_pool: "{{ uuid_pool_name }}"
      lan_connectivity_policy: "{{ fc_lan_conn_policy }}"
      boot_policy: "{{ fc_boot_policy_name }}"
      maintenance_policy: 'default'
      power_control_policy: "{{ power_policy_name }}"
      local_disk_policy: "{{ local_disk_policy_name }}"
      server_pool: "{{ server_pool_name }}"
      san_connectivity_policy: "{{ san_policy_name }}"
      bios_policy: "{{ bios_policy_name}}"
    when: configure_fc is defined
  #
  # Set iSCSI Boot Paramters for the SPT
  #
  - name: Configure Service Profile Template with iSCSI Boot Information
    ucs_managed_objects:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      objects:
      - {
            "module": "ucsmsdk.mometa.ls.LsServer",
            "class": "LsServer",
            "properties": {
                "parent_mo_or_dn": "org-root/org-FlexPod",
                "boot_policy_name": "{{ iscsi_boot_policy_name }}",
                "name": "{{ iscsi_SPT_name }}"
            },
            "children": [
                {
                    "module": "ucsmsdk.mometa.vnic.VnicIScsiBootParams",
                    "class": "VnicIScsiBootParams",
                    "properties": {
                    },
                    "children": [
                        {
                            "module": "ucsmsdk.mometa.vnic.VnicIScsiBootVnic",
                            "class": "VnicIScsiBootVnic",
                            "properties": {
                                "name": "iSCSI-Boot-A"
                            },
                            "children": [
                                {
                                    "module": "ucsmsdk.mometa.vnic.VnicIPv4If",
                                    "class": "VnicIPv4If",
                                    "properties": {
                                    },
                                    "children": [
                                      {
                                          "module": "ucsmsdk.mometa.vnic.VnicIPv4PooledIscsiAddr",
                                          "class": "VnicIPv4PooledIscsiAddr",
                                          "properties": {
                                              ident_pool_name: "{{ iscsi_a_pool_name }}"
                                          }
                                      }
                                    ]
                                },
                                {
                                    "module": "ucsmsdk.mometa.vnic.VnicIScsiStaticTargetIf",
                                    "class": "VnicIScsiStaticTargetIf",
                                    "properties": {
                                        "ip_address": "192.168.10.252",
                                        "name": "iqn.1992-08.com.netapp:sn.2a34dc754e1511eaa17e00a0985b4a87:vs.3",
                                        "priority": "1"
                                    },
                                    "children": [
                                        {
                                            "module": "ucsmsdk.mometa.vnic.VnicLun",
                                            "class": "VnicLun",
                                            "properties": {
                                                "bootable": "no",
                                                "id": "0"
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
