---
#  This task configures the device aliases for the storage and compute devices
# specific variables from the MDS-A/B variables files
#
  - name: Device Alias
    nxos_devicealias:
      distribute: yes
      mode: enhanced
      da:
        - { name: '{{  item.device_name  }}', pwwn: '{{  item.pwwn  }}'}
    with_list: "{{ device_alias_list }}"
